
---

## 🔹 يعني إيه Bag of Words؟

**Bag of Words (BoW)** هو أسلوب في Natural Language Processing
بنستخدمه علشان نحول النص (Text) لأرقام يقدر الكمبيوتر يفهمها.

الفكرة ببساطة:

> بنهمل ترتيب الكلمات، ونركز بس على **عدد مرات تكرار كل كلمة**.

---

## 🔸 مثال بسيط

عندك جملتين:

```
I love programming
I love AI
```

### 1️⃣ نجيب كل الكلمات المختلفة:

```
[I, love, programming, AI]
```

### 2️⃣ نحسب التكرار:

| Sentence           | I | love | programming | AI |
| ------------------ | - | ---- | ----------- | -- |
| I love programming | 1 | 1    | 1           | 0  |
| I love AI          | 1 | 1    | 0           | 1  |

👉 كل جملة اتحولت لـ **Vector (أرقام)**

---

## 🔹 الفكرة الأساسية

* بنعمل **Vocabulary** (قائمة بكل الكلمات)
* كل جملة تتحول لـ **Vector**
* القيمة = عدد مرات ظهور الكلمة

---

## 🔸 ليه بنستخدمه؟

بنستخدم BoW في:

* تصنيف النصوص (Spam / Not Spam)
* تحليل المشاعر (Positive / Negative)
* محركات البحث
* Chatbots

---

## 🔸 مميزاته 👍

* سهل جدًا وبسيط
* سريع في التنفيذ
* كويس كبداية في NLP

---

## 🔸 عيوبه 👎

* ❌ بيهمل ترتيب الكلمات
  (يعني "I love AI" = "AI love I")

* ❌ مبيفهمش المعنى (Semantics)

* ❌ ممكن يعمل Dataset كبير جدًا

---

## 🔥 الخلاصة

**BoW = طريقة بتحول النص لأرقام عن طريق عدّ الكلمات فقط بدون فهم المعنى أو الترتيب.**

---

In [2]:
# bow 
## a simple implementation of a bag of words model for text classification
## using a simple count vectorizer and a multinomial naive bayes classifier
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB





In [7]:

texts = ["I love programming", "I love AI" , "I hate bugs", "I hate errors" , "I love debugging" , "I hate debugging"]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(texts)

print(vectorizer.get_feature_names_out())  # الكلمات
print(X.toarray())

['ai' 'bugs' 'debugging' 'errors' 'hate' 'love' 'programming']
[[0 0 0 0 0 1 1]
 [1 0 0 0 0 1 0]
 [0 1 0 0 1 0 0]
 [0 0 0 1 1 0 0]
 [0 0 1 0 0 1 0]
 [0 0 1 0 1 0 0]]
